### ISSUE TITLE
Publishing to Localhost not working

### ISSUE THREAD

**Issue by andyfensham** [NetCoreTemplates/vuetify-nuxt#4]
I restored this example and ran it locally without any problem.  When I however publish it to localhost on IIS  to NuxtServicestackDemo, I can browse to the service localhost/NuxtServicestackDemo/metadata and run the services hosted in IIS, but the front end code does not seem to run and just have an hourglass showing if I go to localhost/NuxtServicestackDemo or localhost/NuxtServicestackDemo/index

**Comment by mythz** [comment]
Check that you can run the published app, e.g:

    $ npm run publish
    $ cd bin\Release\netcoreapp3.1\publish\
    $ dotnet ProjectName.dll

If you can run the published app then app was built correctly, otherwise look for any JavaScript or Network Request errors in Chrome's WebInspector.

**Comment by andyfensham** [comment]
When I type in dotnet MyApp.dll, the cursor goes one line lower and just
stays there.  Nothing happens.

Tnx

**Comment by mythz** [comment]
ok it runs without issues for me, look at the Debug Inspector for JavaScript or Network errors.

**Comment by andyfensham** [comment]
I checked network traffic.

Although I deployed to localhost/MyApp, I see when I hard refresh my
browser it does not find relevant resources as it is looking for the
resources in  localhost/_nuxt instead of localhost/MyApp/wwwroot/_nuxth.tt

p://localhost/_nuxt/f36cd230d34ac4d306ac.js
http://localhost/_nuxt/f36cd230d34ac4d306ac.js
http://localhost/_nuxt/f36cd230d34ac4d306ac.js

**Comment by andyfensham** [comment]
I did not change anything to the site except adding  server: {
    port: 8083, // default: 3000
    host: "0.0.0.0" // default: localhost
  }, to my nuxt.config.js for running in dev mode as my port 3000 is used
byanother service.

**Comment by mythz** [comment]
Yeah it's the same issue as https://github.com/NetCoreTemplates/vue-nuxt/issues/5 where the Nuxt build generates absolute paths, e.g:

```html
<link rel="preload" href="/_nuxt/a9ffa03f7b76fcee36f7.js" as="script">
```

Expecting the Web App to be [hosted at an virtual domain](https://docs.servicestack.net/netcore-deploy-rsync), e.g. sub.domain.org instead of a Virtual Directory like /VirtualPath.

This [isn't configurable in Nuxt](https://nuxtjs.org/api/configuration-generate) so you'd need a post publish script that rewrites the paths in the generated `index.html` to include your Virtual Path otherwise you'd need to configure an IIS Rerouting rule or something that rewrites `/_nuxt` paths to include your VirtualPath.
